x-fls-ipv4-hosts: &fls-ipv4-hosts
  - "sb-retail.fls.funcom.com:13.107.253.70"
  - "sb-retail.fls.funcom.com:13.107.226.70"

services:
  director:
    extra_hosts: *fls-ipv4-hosts
  gateway:
    extra_hosts: *fls-ipv4-hosts
  text-router:
    extra_hosts: *fls-ipv4-hosts
  survival:
    extra_hosts: *fls-ipv4-hosts
  overmap:
    extra_hosts: *fls-ipv4-hosts
  arrakeen:
    extra_hosts: *fls-ipv4-hosts
  harko-village:
    extra_hosts: *fls-ipv4-hosts
  testing-hephaestus:
    extra_hosts: *fls-ipv4-hosts
  testing-carthag:
    extra_hosts: *fls-ipv4-hosts
  testing-waterfat:
    extra_hosts: *fls-ipv4-hosts
  deep-desert:
    extra_hosts: *fls-ipv4-hosts
  proces-verbal:
    extra_hosts: *fls-ipv4-hosts
  lostharvest-ecolab-a:
    extra_hosts: *fls-ipv4-hosts
  lostharvest-ecolab-b:
    extra_hosts: *fls-ipv4-hosts
  lostharvest-forgottenlab:
    extra_hosts: *fls-ipv4-hosts
  art-of-kanly:
    extra_hosts: *fls-ipv4-hosts
  dungeon-hephaestus:
    extra_hosts: *fls-ipv4-hosts
  dungeon-oldcarthag:
    extra_hosts: *fls-ipv4-hosts
  faction-outpost-atre:
    extra_hosts: *fls-ipv4-hosts
  faction-outpost-hark:
    extra_hosts: *fls-ipv4-hosts
  heighliner-dungeon:
    extra_hosts: *fls-ipv4-hosts
  ecolab-green-089:
    extra_hosts: *fls-ipv4-hosts
  ecolab-green-152:
    extra_hosts: *fls-ipv4-hosts
  ecolab-green-024:
    extra_hosts: *fls-ipv4-hosts
  ecolab-green-195:
    extra_hosts: *fls-ipv4-hosts
  ecolab-green-136:
    extra_hosts: *fls-ipv4-hosts
  overland-m-01:
    extra_hosts: *fls-ipv4-hosts
  overland-s-04:
    extra_hosts: *fls-ipv4-hosts
  overland-s-06:
    extra_hosts: *fls-ipv4-hosts
  bandit-fortress:
    extra_hosts: *fls-ipv4-hosts
  overland-s-07:
    extra_hosts: *fls-ipv4-hosts
  overland-s-08:
    extra_hosts: *fls-ipv4-hosts
  dungeon-thepit:
    extra_hosts: *fls-ipv4-hosts
  deep-desert-pvp:
    extra_hosts: *fls-ipv4-hosts
