[/Script/DuneSandbox.PvpPveSettings]
m_bShouldForceEnablePvpOnAllPartitions=False
;+m_PvpEnabledPartitions=1
;+m_PvpEnabledPartitions=2

[/Script/DuneSandbox.SecurityZonesSubsystem]
m_bAreSecurityZonesEnabled=True

[/DeteriorationSystem.ItemDeteriorationConstants]
UpdateRateInSeconds=1.0

[/Script/DuneSandbox.SandStormConfig]
m_bCoriolisAutoSpawnEnabled=True

[/Script/DuneSandbox.BuildingSettings]
m_MaxNumLandclaimSegments=6
m_BuildingBlueprintMaxExtensions=4
m_BaseBackupMaxExtensions=8
m_bBuildingRestrictionLimitsEnabled=True
