#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="${1:-$repo_root/.env}"
command="${2:-list}"
shift $(( $# > 0 ? 1 : 0 )) || true
shift $(( $# > 0 ? 1 : 0 )) || true
if [[ "$env_file" != /* ]]; then env_file="$repo_root/$env_file"; fi
config_file="${DUNE_SIETCH_CONFIG_FILE:-$repo_root/backups/admin-panel/sietches.json}"
overlay_file="${DUNE_SIETCH_OVERLAY_FILE:-$repo_root/backups/admin-panel/compose.sietches.generated.yaml}"
backup_dir="$repo_root/backups/sietches"
mkdir -p "$(dirname "$config_file")" "$(dirname "$overlay_file")" "$backup_dir"

read_env() { sed -nE "s/^$1=//p" "$env_file" 2>/dev/null | tail -1; }
bool_true() { case "${1,,}" in 1|true|yes|on) return 0 ;; *) return 1 ;; esac; }
compose=(docker compose --env-file "$env_file" -f "$repo_root/compose.yaml" -f "$repo_root/compose.allmaps.yaml")
psql_q() { "${compose[@]}" exec -T postgres psql -X -v ON_ERROR_STOP=1 -U dune -d dune "$@"; }

require_execute() {
  local execute="${1:-}" allowed current
  [[ "$execute" == "--execute" ]] || { printf 'dry-run only; append --execute to commit\n' >&2; return 64; }
  bool_true "$(read_env DUNE_SIETCH_MUTATIONS_ENABLED)" || { printf 'DUNE_SIETCH_MUTATIONS_ENABLED is not true\n' >&2; return 77; }
  allowed="$(read_env DUNE_SIETCH_ALLOWED_HOST)"; current="$(hostname -s)"
  [[ -n "$allowed" && "$allowed" == "$current" ]] || { printf 'refusing Sietch mutation: hostname=%s allowed_host=%s\n' "$current" "${allowed:-unset}" >&2; return 77; }
}

backup_db() {
  local path="$backup_dir/sietches-$(date -u +%Y%m%dT%H%M%SZ).dump"
  "${compose[@]}" exec -T postgres pg_dump -Fc -U dune -d dune > "$path"
  chmod 600 "$path"
  printf '%s' "$path"
}

list_sietches() {
  psql_q -P pager=off -c "
select wp.partition_id, wp.dimension_index, coalesce(wp.label,''), wp.blocked,
       coalesce(wp.server_id,''), coalesce(fs.connected_players,0),
       coalesce(host(fs.game_addr),''), coalesce(fs.game_port,0)
from dune.world_partition wp
left join dune.farm_state fs on fs.server_id=wp.server_id
where wp.map='Survival_1'
order by wp.dimension_index,wp.partition_id;"
}

write_setting() {
  local partition="$1" display="$2" password="$3"
  PARTITION="$partition" DISPLAY="$display" PASSWORD="$password" CONFIG_FILE="$config_file" python3 - <<'PY'
import json, os
from pathlib import Path
p=Path(os.environ["CONFIG_FILE"])
try: data=json.loads(p.read_text())
except Exception: data={"partitions":{}}
row=data.setdefault("partitions",{}).setdefault(os.environ["PARTITION"],{})
row["display_name"]=os.environ["DISPLAY"]
row["password"]=os.environ["PASSWORD"]
tmp=p.with_name(f".{p.name}.tmp.{os.getpid()}")
tmp.write_text(json.dumps(data,indent=2,sort_keys=True)+"\n")
tmp.chmod(0o600); tmp.replace(p)
PY
}

apply_setting_labels() {
  [[ -f "$config_file" ]] || return 0
  while IFS=$'\t' read -r partition display; do
    [[ "$partition" =~ ^[0-9]+$ && -n "$display" ]] || continue
    psql_q -q -v pid="$partition" -v label="$display" -c "update dune.world_partition set label=:'label' where partition_id=:'pid'::bigint and map='Survival_1';" >/dev/null
  done < <(CONFIG_FILE="$config_file" python3 - <<'PY'
import json, os
from pathlib import Path
try: rows=json.loads(Path(os.environ["CONFIG_FILE"]).read_text()).get("partitions",{})
except Exception: rows={}
for pid,row in rows.items():
    display=str(row.get("display_name") or "").replace("\t"," ").replace("\n"," ").strip()
    if str(pid).isdigit() and display: print(f"{pid}\t{display}")
PY
)
}

render_overlay() {
  local rows
  rows="${DUNE_SIETCH_TEST_ROWS:-}"
  if [[ -z "$rows" ]]; then
    rows="$(psql_q -qAt -F $'\t' -c "
select partition_id,dimension_index,coalesce(label,'')
from dune.world_partition
where map='Survival_1' and not blocked and dimension_index > 0
order by dimension_index,partition_id;")"
  fi
  SIETCH_ROWS="$rows" CONFIG_FILE="$config_file" OVERLAY_FILE="$overlay_file" REPO_ROOT="$repo_root" python3 - <<'PY'
import json, os
from pathlib import Path
root=Path(os.environ["REPO_ROOT"])
cfg={}
try: cfg=json.loads(Path(os.environ["CONFIG_FILE"]).read_text()).get("partitions",{})
except Exception: pass
lines=["# Generated by scripts/sietches.sh; contains local Sietch passwords.","services:"]
rows=[]
for raw in os.environ.get("SIETCH_ROWS","").splitlines():
    parts=raw.split("\t",2)
    if len(parts)==3: rows.append((int(parts[0]),int(parts[1]),parts[2]))
if not rows: lines.append("  {}")
for pid,dim,label in rows:
    if not 1 <= dim <= 63: raise SystemExit(f"dimension {dim} is outside supported range 1..63")
    service=f"sietch-{pid}"
    game_port=8000+dim; igw_port=8100+dim; ip=f"172.31.240.{128+dim}"
    local=cfg.get(str(pid),{})
    display=str(local.get("display_name") or label or f"Sietch {dim+1}")
    password=str(local.get("password") or "")
    command=[
      "/workspace/scripts/run_server_safe.sh", "-FarmRegion=${WORLD_REGION}",
      "-ini:engine:[FuncomLiveServices]:ServiceAuthToken=${FLS_SECRET}",
      "-ini:engine:[FuncomLiveServices]:DefaultFlsEnvironment=${DUNE_FLS_ENV:-retail}",
      "-ini:engine:[FuncomLiveServices]:ServerCommandsAuthToken=${DUNE_SERVER_COMMANDS_AUTH_TOKEN:-}",
      "-ini:engine:[ConsoleVariables]:server.NotificationSystem.Enabled=${DUNE_SERVER_NOTIFICATION_SYSTEM_ENABLED:-false}",
      "-ini:engine:[OnlineSubsystem]:ServerName=${WORLD_UNIQUE_NAME}",
      f"-ini:engine:[ConsoleVariables]:Bgd.ServerLoginPassword={password}",
      "-ini:engine:[OnlineSubsystem]:DatacenterId=${WORLD_DATACENTER_ID}",
      "-ini:game:[DuneDatabaseInterfacePSQL]:DatabaseHost=postgres:5432",
      "-ini:game:[DuneDatabaseInterfacePSQL]:DatabaseUser=dune",
      "-ini:game:[DuneDatabaseInterfacePSQL]:DatabasePassword=${POSTGRES_DUNE_PASSWORD}",
      "-RMQGameTlsEnabled=true", "-ExternalAddress=${EXTERNAL_ADDRESS}",
      "--RMQGameHostname=game-rmq", "--RMQGamePort=5672",
      "--RMQAdminHostname=admin-rmq", "--RMQAdminPort=5672", "-MultiHome=$$POD_IP",
      "-ini:game:[/Script/DuneSandbox.BuildingSettings]:m_BaseBackupToolTimeRestrictionInSeconds=0",
      f"-Port={game_port}", f"-IGWPort={igw_port}", f"-PartitionIndex={pid}"]
    lines += [f"  {service}:","    extends:",f"      file: {json.dumps(str(root/'compose.yaml'))}","      service: survival",
      f"    container_name: dune-sietch-{pid}","    restart: unless-stopped",
      "    labels:","      com.dune.sietch: \"true\"",f"      com.dune.partition: {json.dumps(str(pid))}",f"      com.docker.compose.service: {json.dumps(service)}",
      f"    command: {json.dumps(command)}","    environment:",f"      POD_IP: {json.dumps(ip)}",f"      DUNE_SERVER_DISPLAY_NAME: {json.dumps(display)}",f"      DUNE_SERVER_LOGIN_PASSWORD: {json.dumps(password)}",
      "    ports: !override",f"      - {json.dumps(f'{game_port}:{game_port}/udp')}",f"      - {json.dumps(f'{igw_port}:{igw_port}/udp')}",
      "    volumes: !override",f"      - {json.dumps(str(root)+':/workspace:ro')}",f"      - {json.dumps(str(root/'data'/'server-saved'/service)+':/home/dune/server/DuneSandbox/Saved')}",
      "    networks:","      default:",f"        ipv4_address: {ip}"]
p=Path(os.environ["OVERLAY_FILE"]); p.write_text("\n".join(lines)+"\n"); p.chmod(0o600)
PY
  printf '%s\n' "$overlay_file"
}

active_partition_ids() {
  psql_q -qAt -c "select partition_id from dune.world_partition where map='Survival_1' and not blocked order by dimension_index,partition_id;"
}

stop_inactive_managed() {
  local active container pid players
  active="$(active_partition_ids)"
  while IFS= read -r container; do
    [[ -n "$container" ]] || continue
    pid="$(docker inspect -f '{{ index .Config.Labels "com.dune.partition" }}' "$container")"
    grep -qx "$pid" <<< "$active" && continue
    players="$(psql_q -qAt -v pid="$pid" -c "select coalesce(fs.connected_players,0) from dune.world_partition wp left join dune.farm_state fs on fs.server_id=wp.server_id where wp.partition_id=:'pid'::bigint;")"
    [[ "${players:-0}" == "0" ]] || { printf 'refusing to stop %s: connected_players=%s\n' "$container" "$players" >&2; return 75; }
    docker stop -t 120 "$container" >/dev/null
    docker rm "$container" >/dev/null
  done < <(docker ps -a --filter label=com.dune.sietch=true --format '{{.Names}}')
}

reconcile() {
  local execute="${1:-}" overlay services
  if [[ "$execute" != "--execute" ]]; then
    overlay="$(render_overlay)"
    printf 'dry-run: rendered %s; no containers were changed\n' "$overlay"
    return 0
  fi
  require_execute "$execute"
  stop_inactive_managed
  apply_setting_labels
  overlay="$(render_overlay)"
  mapfile -t services < <(sed -nE 's/^  (sietch-[0-9]+):$/\1/p' "$overlay")
  if ((${#services[@]})); then
    docker compose --env-file "$env_file" -f "$repo_root/compose.yaml" -f "$repo_root/compose.allmaps.yaml" -f "$overlay" up -d --no-deps "${services[@]}"
  fi
}

set_active() {
  local count="$1" execute="${2:-}"
  [[ "$count" =~ ^[0-9]+$ ]] && ((count >= 1 && count <= 64)) || { printf 'active Sietches must be 1..64\n' >&2; return 2; }
  printf 'plan: set Survival_1 active dimensions to %s; additional ports use udp/8001-8063 and udp/8101-8163\n' "$count"
  [[ "$execute" == "--execute" ]] || return 0
  require_execute "$execute"
  local occupied
  occupied="$(psql_q -qAt -v target="$count" -c "with ranked as (select partition_id,server_id,row_number() over(order by dimension_index,partition_id) ord from dune.world_partition where map='Survival_1') select string_agg(ranked.partition_id::text,',') from ranked join dune.farm_state fs on fs.server_id=ranked.server_id where ranked.ord > :'target'::integer and coalesce(fs.connected_players,0)>0;")"
  [[ -z "$occupied" ]] || { printf 'refusing active-count reduction; connected players remain in partitions %s\n' "$occupied" >&2; return 75; }
  local backup; backup="$(backup_db)"
  psql_q -v target="$count" -c "
set search_path=dune,public;
do \$\$
declare current_count integer; next_dim integer;
begin
  select count(*),coalesce(max(dimension_index),-1)+1 into current_count,next_dim from dune.world_partition where map='Survival_1';
  while current_count < $count loop
    insert into dune.world_partition(partition_id,server_id,map,partition_definition,dimension_index,blocked,label)
    select nextval('dune.world_partition_partition_id_seq'),null,map,partition_definition,next_dim,false,null
    from dune.world_partition where map='Survival_1' order by dimension_index,partition_id limit 1;
    current_count:=current_count+1; next_dim:=next_dim+1;
  end loop;
end \$\$;
with ranked as (select partition_id,row_number() over(order by dimension_index,partition_id) ord from dune.world_partition where map='Survival_1')
update dune.world_partition wp set blocked=(ranked.ord > $count) from ranked where wp.partition_id=ranked.partition_id;
select dune.update_partition_labels(true);"
  printf 'database backup: %s\n' "$backup"
  reconcile --execute
}

set_settings() {
  local partition="$1" display="$2" password="$3" execute="${4:-}" players backup
  [[ "$partition" =~ ^[0-9]+$ ]] || { printf 'partition id must be numeric\n' >&2; return 2; }
  [[ "$display" != *$'\n'* && "$password" != *$'\n'* && ${#display} -le 100 && ${#password} -le 100 ]] || { printf 'display/password is invalid\n' >&2; return 2; }
  printf 'plan: update display name and %s password for partition %s\n' "$([[ -n "$password" ]] && printf set || printf clear)" "$partition"
  [[ "$execute" == "--execute" ]] || return 0
  require_execute "$execute"
  players="$(psql_q -qAt -v pid="$partition" -c "select coalesce(fs.connected_players,0) from dune.world_partition wp left join dune.farm_state fs on fs.server_id=wp.server_id where wp.partition_id=:'pid'::bigint and wp.map='Survival_1';")"
  [[ -n "$players" ]] || { printf 'unknown Survival_1 partition: %s\n' "$partition" >&2; return 1; }
  [[ "$players" == "0" ]] || { printf 'refusing settings change: connected_players=%s\n' "$players" >&2; return 75; }
  backup="$(backup_db)"
  if [[ -f "$config_file" ]]; then cp -a "$config_file" "$backup_dir/sietches-config-before-$(date -u +%Y%m%dT%H%M%SZ).json"; fi
  write_setting "$partition" "$display" "$password"
  psql_q -v pid="$partition" -v label="$display" -c "update dune.world_partition set label=nullif(:'label','') where partition_id=:'pid'::bigint and map='Survival_1';"
  printf 'database backup: %s\n' "$backup"
  reconcile --execute
}

stop_managed() {
  local execute="${1:-}" container
  require_execute "$execute"
  while IFS= read -r container; do
    [[ -n "$container" ]] || continue
    docker stop -t 120 "$container" >/dev/null
  done < <(docker ps --filter label=com.dune.sietch=true --format '{{.Names}}')
}

case "$command" in
  list|status) list_sietches ;;
  render) render_overlay ;;
  reconcile) reconcile "${1:-}" ;;
  set-active) [[ $# -ge 1 ]] || { printf 'set-active requires COUNT [--execute]\n' >&2; exit 2; }; set_active "$1" "${2:-}" ;;
  set-settings) [[ $# -ge 3 ]] || { printf 'set-settings requires PARTITION DISPLAY PASSWORD [--execute]\n' >&2; exit 2; }; set_settings "$1" "$2" "$3" "${4:-}" ;;
  stop-managed) stop_managed "${1:-}" ;;
  *) printf 'Usage: %s [ENV_FILE] <list|render|reconcile [--execute]|set-active COUNT [--execute]|set-settings PARTITION DISPLAY PASSWORD [--execute]|stop-managed [--execute]>\n' "$0" >&2; exit 2 ;;
esac
