#!/usr/bin/env python3
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "ue4ss-package-runtime-trace.sh"


class PackageRuntimeTraceRunnerTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.source = SCRIPT.read_text(encoding="utf-8")

    def test_runner_is_host_guarded_and_override_is_explicit(self):
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_HOST:-kspls0", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_ALLOW_ANY_HOST", self.source)
        self.assertIn("refusing package runtime trace", self.source)

    def test_runner_uses_build_validating_plan_generator(self):
        self.assertIn("plan-ue4ss-package-runtime-trace.py", self.source)
        self.assertIn("summarize-ue4ss-package-runtime-trace-evidence.py", self.source)
        self.assertIn("export-ue4ss-package-promotion-env.py", self.source)
        self.assertIn("review-ue4ss-package-abi.py", self.source)
        self.assertIn("summarize-ue4ss-package-promotion-dir.py", self.source)
        self.assertIn("--pid", self.source)
        self.assertIn('"$trace_log" --pid "$pid" --trace-plan-json "$trace_plan_json" --format json >"$evidence_json"', self.source)
        self.assertIn('refresh_trace_plan_outputs "${pid:-}"', self.source)
        self.assertIn("--gdb-out", self.source)
        self.assertIn("server-ue4ss-package-external-symbol-plan.json", self.source)
        self.assertIn("anchor_args", self.source)
        self.assertIn("seed_address_args", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_SEED_ADDRESS", self.source)
        self.assertIn("--seed-address", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_METHOD_CANDIDATES", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_METHOD_LIMIT", self.source)
        self.assertIn("--method-candidates \"$method_candidates\"", self.source)
        self.assertIn("--method-limit \"$method_limit\"", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_ROUTE_ADDRESS", self.source)
        self.assertIn("--route-address", self.source)
        self.assertIn("route_address_args", self.source)
        self.assertIn('local raw="${anchor//,/ }"', self.source)
        self.assertIn('"${trace_anchor_args[@]}"', self.source)
        self.assertNotIn('--anchor "$anchor"', self.source)
        self.assertIn('anchor_count=$(( ${#trace_anchor_args[@]} / 2 ))', self.source)
        self.assertIn('effective_limit="$anchor_count"', self.source)
        self.assertIn('--limit "$effective_limit"', self.source)

    def test_runner_process_match_is_configurable_for_non_dune_targets(self):
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_PID", self.source)
        self.assertIn('explicit_pid="${DUNE_UE4SS_PACKAGE_TRACE_PID:-}"', self.source)
        self.assertIn("container_was_set=0", self.source)
        self.assertIn('if [[ "${2+x}" == x ]]; then', self.source)
        self.assertIn('if [[ -n "$explicit_pid" && "$container_was_set" != "1" ]]; then', self.source)
        self.assertIn('container="pid-$explicit_pid"', self.source)
        self.assertIn("required_host_was_set=0", self.source)
        self.assertIn('if [[ "${DUNE_UE4SS_PACKAGE_TRACE_HOST+x}" == x ]]; then', self.source)
        self.assertIn('expected_host="$required_host"', self.source)
        self.assertIn('if [[ -n "$explicit_pid" && "$required_host_was_set" != "1" ]]; then', self.source)
        self.assertIn('expected_host="$host"', self.source)
        self.assertIn('if [[ -n "$explicit_pid" ]]; then', self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_PID must be numeric", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_PID does not exist", self.source)
        self.assertIn('printf \'%s\\n\' "$explicit_pid"', self.source)
        self.assertIn("assert_runtime_selector_args", self.source)
        self.assertIn("package runtime trace container selector must be non-empty and single-line", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_PROCESS_PATTERN must be non-empty and single-line", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_PROCESS_PATTERN", self.source)
        self.assertIn('process_pattern="${DUNE_UE4SS_PACKAGE_TRACE_PROCESS_PATTERN:-DuneSandboxServer-Linux-Shipping}"', self.source)
        self.assertIn('awk -v pattern="$process_pattern"', self.source)
        self.assertIn("|| true", self.source)
        self.assertIn("no process matching '$process_pattern' found", self.source)

    def test_runner_status_writes_evidence_and_promotion_artifacts(self):
        status_start = self.source.index("do_status() {")
        status_body = self.source[status_start : self.source.index("\n}", status_start)]
        self.assertIn("assert_host", status_body)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_EVIDENCE_JSON", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_EVIDENCE_MD", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_ABI_REVIEW_JSON", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_ABI_REVIEW_MD", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_PROMOTION_MD", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_PROMOTION_JSON", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_ALL_FAMILY_DIR", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_ALL_FAMILY_SUMMARY_MD", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_ALL_FAMILY_SUMMARY_JSON", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_CANARY_SERVER_LOG", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_NEXT_CANARY_JSON", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_NEXT_CANARY_ENV", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_NEXT_ACTION_JSON", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_NEXT_ACTION_MD", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_REVIEW_BUNDLE_DIR", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_ROUTE_SLOT_RECOVERY_VERIFY_JSON", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_ROUTE_SLOT_RECOVERY_VERIFY_MD", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_PLAN_JSON", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_PLAN_MD", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_SIGNATURE_FAMILY", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_HIT_INDEX", self.source)
        self.assertIn('rm -f \\', self.source)
        self.assertIn('"$evidence_json" "$evidence_md"', self.source)
        self.assertIn('"$abi_review_json" "$abi_review_md"', self.source)
        self.assertIn('"$promotion_json" "$promotion_md"', self.source)
        self.assertIn('"$trace_plan_json" "$trace_plan_md"', self.source)
        self.assertIn('"$next_action_json" "$next_action_md"', self.source)
        self.assertIn('"$next_canary_json" "$next_canary_env"', self.source)
        self.assertIn('rm -rf "$all_family_dir"', self.source)
        self.assertIn('anchor="${DUNE_UE4SS_PACKAGE_TRACE_ANCHOR:-LoadPackage,LoadObject}"', self.source)
        self.assertIn('signature_family="${DUNE_UE4SS_PACKAGE_TRACE_SIGNATURE_FAMILY:-LoadPackage}"', self.source)
        self.assertIn('hit_index="${DUNE_UE4SS_PACKAGE_TRACE_HIT_INDEX:-auto}"', self.source)
        self.assertIn("assert_signature_family", self.source)
        self.assertIn("assert_anchor_args", self.source)
        self.assertIn("unsupported DUNE_UE4SS_PACKAGE_TRACE_ANCHOR", self.source)
        self.assertIn("unsupported DUNE_UE4SS_PACKAGE_TRACE_SEED_ADDRESS", self.source)
        self.assertIn("assert_trace_limit", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_LIMIT must be a positive integer", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_METHOD_LIMIT must be a non-negative integer", self.source)
        self.assertIn("assert_hit_index", self.source)
        self.assertIn('"$hit_index" != "auto"', self.source)
        self.assertIn('--hit-index "$hit_index"', self.source)
        self.assertIn("StaticLoadObject|StaticLoadClass|LoadObject|LoadPackage|ResolveName", self.source)
        self.assertIn('--signature-family "$signature_family"', self.source)
        self.assertIn("--abi-review-json \"$abi_review_json\"", self.source)
        self.assertIn("promotion_review_args", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_REVIEWED_TARGET_IMAGE", self.source)
        self.assertIn("--reviewed-target-image", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_REVIEWED_ABI", self.source)
        self.assertIn("--reviewed-abi", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_REVIEWED_CLASS_ROOT", self.source)
        self.assertIn("--reviewed-class-root", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_TCHAR_UNIT_BYTES", self.source)
        self.assertIn("--tchar-unit-bytes", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_ALLOW_NATIVE_INVOKE", self.source)
        self.assertIn("--allow-native-invoke", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_FINAL_NATIVE_CALL", self.source)
        self.assertIn("--final-native-call", self.source)
        self.assertIn("abi_review_json=$abi_review_json", self.source)
        self.assertIn("abi_review=$abi_review_md", self.source)
        self.assertIn("promotion_json=$promotion_json", self.source)
        self.assertIn("promotion_preview=$promotion_md", self.source)
        self.assertIn("write_all_family_reviews", self.source)
        self.assertIn('rm -f "$all_family_summary_json" "$all_family_summary_md"', self.source)
        self.assertIn("candidate_families", self.source)
        self.assertIn('data.get("concreteReviewPriority") or data.get("reviewPriority")', self.source)
        self.assertIn('print(f"{rank}\\t{family}\\t{hit_index}")', self.source)
        self.assertIn("if not isinstance(hit_index, int):", self.source)
        self.assertIn("review-priority hitIndex must be concrete integer", self.source)
        self.assertIn("hit_index = int(raw_hit_index)", self.source)
        self.assertIn('"hitIndex": hit_index', self.source)
        self.assertIn("json.dump(", self.source)
        self.assertIn("review-priority.json", self.source)
        self.assertIn("dune-ue4ss-package-review-priority/v1", self.source)
        self.assertIn('--hit-index "${review_hit_index:-auto}"', self.source)
        self.assertEqual(self.source.count('--hit-index "${review_hit_index:-auto}"'), 4)
        self.assertIn("printed.add(family)", self.source)
        self.assertIn("all_family_review_dir=$all_family_dir", self.source)
        self.assertIn("all_family_summary_md=$all_family_summary_md", self.source)
        self.assertIn("all_family_summary_json=$all_family_summary_json", self.source)
        self.assertIn("--package-promotion-dir", self.source)
        self.assertIn("--package-promotion-summary-json", self.source)
        self.assertIn('package_args+=(--package-promotion-summary-json "$all_family_summary_json")', self.source)
        self.assertIn('package_args+=(--package-promotion-dir "$all_family_dir")', self.source)
        self.assertIn('echo "${package_args[$i]#--}=${package_args[$((i + 1))]}"', self.source)
        self.assertIn('"${package_args[@]}" --format json', self.source)
        self.assertIn('"${package_args[@]}" --format env', self.source)
        self.assertIn("print_next_canary_preview", self.source)
        self.assertIn("--next-canary-preview--", self.source)
        self.assertIn("--package-promotion-json", self.source)
        self.assertIn("--max-stage lua-dispatch", self.source)
        self.assertIn("write_next_action", self.source)
        self.assertIn("plan-ue4ss-package-next-action.py", self.source)
        self.assertIn("refresh_trace_plan_outputs", self.source)
        self.assertIn('local tmp_json="${trace_plan_json}.tmp.$$"', self.source)
        self.assertIn('local tmp_md="${trace_plan_md}.tmp.$$"', self.source)
        self.assertIn('rm -f "$tmp_json" "$tmp_md" "$trace_plan_json" "$trace_plan_md"', self.source)
        self.assertIn("failed to refresh package runtime trace plan JSON", self.source)
        self.assertIn("failed to refresh package runtime trace plan markdown", self.source)
        self.assertIn('mv "$tmp_json" "$trace_plan_json"', self.source)
        self.assertIn('mv "$tmp_md" "$trace_plan_md"', self.source)
        self.assertIn("require_trace_plan_ready", self.source)
        self.assertIn('require_trace_plan_ready "$trace_plan_json"', self.source)
        self.assertIn('refresh_trace_plan_outputs "$runtime_pid" || true', self.source)
        refresh_start = self.source.index("refresh_trace_plan_outputs() {")
        refresh_body = self.source[refresh_start : self.source.index("\n}", refresh_start)]
        self.assertIn("assert_anchor_args", refresh_body)
        self.assertIn("assert_trace_limit", refresh_body)
        self.assertIn('local tmp_next_action_json="${next_action_json}.tmp.$$"', self.source)
        self.assertIn('local tmp_next_action_md="${next_action_md}.tmp.$$"', self.source)
        self.assertIn('rm -f "$tmp_next_action_json" "$tmp_next_action_md"', self.source)
        self.assertIn('rm -f "$tmp_next_action_json" "$tmp_next_action_md" "$next_action_json" "$next_action_md"', self.source)
        self.assertIn("failed to write package next-action JSON", self.source)
        self.assertIn("failed to write package next-action markdown", self.source)
        self.assertIn('mv "$tmp_next_action_json" "$next_action_json"', self.source)
        self.assertIn('mv "$tmp_next_action_md" "$next_action_md"', self.source)
        self.assertIn("next_action_json=$next_action_json", self.source)
        self.assertIn('--promotion-json "$promotion_json"', self.source)
        self.assertIn('local runtime_pid="${2:-}"', self.source)
        self.assertIn('trace_plan_runtime_args=(--pid "$runtime_pid")', self.source)
        self.assertIn('trace_plan_runtime_args=(--base 0x100000)', self.source)
        self.assertIn('"${trace_plan_runtime_args[@]}"', self.source)
        self.assertIn('write_next_action "$trace_log" "${pid:-}"', self.source)
        self.assertIn("--trace-plan-json", self.source)
        self.assertIn("--process-pattern", self.source)
        self.assertIn("--target-pid", self.source)
        self.assertIn('local effective_target_pid="$explicit_pid"', self.source)
        self.assertIn('effective_target_pid="$runtime_pid"', self.source)
        self.assertIn('--target-pid "$effective_target_pid"', self.source)
        self.assertIn("--trace-host", self.source)
        self.assertIn('if [[ "$required_host_was_set" == "1" ]]; then', self.source)
        self.assertIn('next_action_args+=(--trace-host "$required_host")', self.source)
        self.assertIn("traceHost=$required_host", self.source)
        self.assertIn('"$explicit_pid"', self.source)
        self.assertIn('"$process_pattern"', self.source)
        self.assertIn('trace_plan_md="${DUNE_UE4SS_PACKAGE_TRACE_PLAN_MD:-/tmp/ue4ss-package-runtime-trace-plan.md}"', self.source)
        self.assertIn('trace_plan_json="${DUNE_UE4SS_PACKAGE_TRACE_PLAN_JSON:-/tmp/ue4ss-package-runtime-trace-plan.json}"', self.source)
        self.assertIn('--format markdown >"$trace_plan_md"', self.source)
        self.assertIn('--format json >"$trace_plan_json"', self.source)
        self.assertIn("package runtime trace plan is blocked", self.source)
        self.assertIn("package runtime trace plan selected no seeds", self.source)
        self.assertIn("write_review_bundle", self.source)
        self.assertIn("write_bundle_trace_plan_manifest_fields", self.source)
        self.assertIn('write_bundle_trace_plan_manifest_fields "$trace_plan_json"', self.source)
        self.assertIn("sourceTracePlan", self.source)
        self.assertIn("tracePlanSourceExternalPlan", self.source)
        self.assertIn("tracePlanBase", self.source)
        self.assertIn("tracePlanExpectedBuildId", self.source)
        self.assertIn("tracePlanRuntimeBuildId", self.source)
        self.assertIn("tracePlanSeedCount", self.source)
        self.assertIn("tracePlanSeedOffsets", self.source)
        self.assertIn("tracePlanSelectedByFamily", self.source)
        self.assertIn("tracePlanBlockerCount", self.source)
        self.assertIn("tracePlanRecommendedAnchor", self.source)
        self.assertIn("tracePlanRecommendedLimit", self.source)
        self.assertIn("tracePlanRecommendedSignatureFamily", self.source)
        self.assertIn("tracePlanRecommendedHitIndex", self.source)
        self.assertIn("write_bundle_image_manifest_fields", self.source)
        self.assertIn("review_bundle_manifest=$manifest", self.source)
        self.assertIn("review_bundle_sha256=$bundle/SHA256SUMS", self.source)
        self.assertIn('mkdir -p "$review_bundle_root"', self.source)
        self.assertIn('while ! mkdir "$bundle" 2>/dev/null; do', self.source)
        self.assertIn('bundle="$review_bundle_root/$stamp-$suffix"', self.source)
        self.assertIn("schema=dune-ue4ss-package-review-bundle/v1", self.source)
        self.assertIn("processPattern=$process_pattern", self.source)
        self.assertIn("evidence_pid_field", self.source)
        self.assertIn("effective_trace_pid=\"$explicit_pid\"", self.source)
        self.assertIn("tracePid=$effective_trace_pid", self.source)
        self.assertIn("playerGuardPhase=$DUNE_UE4SS_PACKAGE_TRACE_PLAYER_GUARD_PHASE", self.source)
        self.assertIn("playerGuardPartition=$DUNE_UE4SS_PACKAGE_TRACE_PLAYER_GUARD_PARTITION", self.source)
        self.assertIn("playerGuardConnectedPlayers=$DUNE_UE4SS_PACKAGE_TRACE_PLAYER_GUARD_CONNECTED_PLAYERS", self.source)
        self.assertIn("sourceLogExists", self.source)
        self.assertIn("sourceLogSha256", self.source)
        self.assertIn("sourceEvidenceJson", self.source)
        self.assertIn("sourceEvidenceJsonSha256", self.source)
        self.assertIn("import hashlib", self.source)
        self.assertIn("def file_sha256(candidate):", self.source)
        self.assertIn('"sourceEvidenceJson": data.get("sourceEvidenceJson") or str(path)', self.source)
        self.assertIn('"sourceEvidenceJsonSha256": data.get("sourceEvidenceJsonSha256") or file_sha256(path)', self.source)
        self.assertIn("evidencePid", self.source)
        self.assertIn("tracePidMatchesRequested", self.source)
        self.assertIn("imageRangeSource", self.source)
        self.assertIn("imageBase", self.source)
        self.assertIn("imageStart", self.source)
        self.assertIn("imageEnd", self.source)
        self.assertIn("imagePath", self.source)
        self.assertIn("imagePerms", self.source)
        self.assertIn("$all_family_dir", self.source)
        self.assertIn("$next_canary_json", self.source)
        self.assertIn("$next_canary_env", self.source)
        self.assertIn("review-priority.json", self.source)
        self.assertIn("sha256sum > SHA256SUMS", self.source)
        self.assertIn("verify-ue4ss-package-review-bundle.py", self.source)
        self.assertIn("verify-ue4ss-package-route-slot-recovery.py", self.source)
        self.assertIn("write_route_slot_recovery_verification", self.source)
        self.assertIn("route_slot_recovery_verify_json=$route_slot_recovery_verify_json", self.source)
        self.assertIn("route_slot_recovery_verify=$route_slot_recovery_verify_md", self.source)
        self.assertIn("$route_slot_recovery_verify_json", self.source)
        self.assertIn("$route_slot_recovery_verify_md", self.source)
        self.assertIn("review_bundle_verify_json=$review_bundle_verify_json", self.source)
        self.assertIn("review_bundle_verify=$review_bundle_verify_md", self.source)
        self.assertIn('find "$source" -type f -print -quit', self.source)
        self.assertIn("continue", self.source)

    def test_runner_status_reports_whether_gdb_is_running(self):
        status_start = self.source.index("do_status() {")
        status_body = self.source[status_start : self.source.index("\n}", status_start)]

        self.assertIn('echo "gdb_pid=$gdb_pid"', status_body)
        self.assertIn('if ps -p "$gdb_pid" -o pid=,stat=,cmd= 2>/dev/null; then', status_body)
        self.assertIn('echo "gdb_running=true"', status_body)
        self.assertIn('echo "gdb_running=false"', status_body)
        self.assertIn("package trace gdb pid file exists but gdb is not running", status_body)

    def test_runner_has_non_attaching_preflight(self):
        self.assertIn("do_preflight() {", self.source)
        preflight_start = self.source.index("do_preflight() {")
        preflight_body = self.source[preflight_start : self.source.index("\n}", preflight_start)]
        self.assertIn("assert_host", preflight_body)
        self.assertIn("assert_runtime_selector_args", preflight_body)
        self.assertIn("assert_signature_family", preflight_body)
        self.assertIn("assert_anchor_args", preflight_body)
        self.assertIn("assert_trace_limit", preflight_body)
        self.assertIn("assert_hit_index", preflight_body)
        self.assertIn("assert_promotion_review_args", preflight_body)
        self.assertIn('assert_trace_output_paths "$trace_log"', preflight_body)
        self.assertIn("external plan not found", preflight_body)
        self.assertIn("server_pid", preflight_body)
        self.assertIn('refresh_trace_plan_outputs "$pid"', preflight_body)
        self.assertIn('require_trace_plan_ready "$trace_plan_json"', preflight_body)
        self.assertIn("docker_container_exists", self.source)
        self.assertIn("docker container not found", preflight_body)
        self.assertIn("gdb binary not found", preflight_body)
        self.assertIn("sudo -n is required for gdb attach", preflight_body)
        self.assertIn("preflight=ok", preflight_body)
        self.assertIn("route_address=$route_address", preflight_body)
        self.assertIn("ptrace_scope", preflight_body)
        self.assertIn('sudo -n "$gdb_bin" -q -p "$pid"', self.source)
        self.assertIn("preflight)", self.source)
        self.assertIn("use preflight|arm|stop|status", self.source)
        self.assertNotIn(" -p \"$pid\" -x \"$gdb_cmd\"", preflight_body)

    def test_runner_rejects_multiline_output_paths_before_writes(self):
        self.assertIn("assert_single_line_path", self.source)
        self.assertIn("assert_trace_output_paths", self.source)
        self.assertIn("must be a non-empty single-line path", self.source)
        self.assertIn("remove_generated_file() {", self.source)
        self.assertIn('rm -f "$path" 2>/dev/null || sudo -n rm -f "$path"', self.source)
        self.assertIn('assert_single_line_path "DUNE_UE4SS_PACKAGE_TRACE_PLAN" "$external_plan"', self.source)
        self.assertIn('assert_single_line_path "DUNE_UE4SS_PACKAGE_TRACE_NEXT_ACTION_JSON" "$next_action_json"', self.source)
        self.assertIn('assert_single_line_path "DUNE_UE4SS_PACKAGE_TRACE_NEXT_ACTION_MD" "$next_action_md"', self.source)
        self.assertIn('assert_single_line_path "DUNE_UE4SS_PACKAGE_TRACE_LIVE_RUNBOOK_JSON" "$live_trace_runbook_json"', self.source)
        self.assertIn('assert_single_line_path "DUNE_UE4SS_PACKAGE_TRACE_REVIEW_BUNDLE_DIR" "$review_bundle_root"', self.source)
        self.assertIn('assert_single_line_path "DUNE_UE4SS_PACKAGE_TRACE_REVIEW_BUNDLE_VERIFY_JSON" "$review_bundle_verify_json"', self.source)
        self.assertIn('assert_single_line_path "DUNE_UE4SS_PACKAGE_TRACE_REVIEW_BUNDLE_VERIFY_MD" "$review_bundle_verify_md"', self.source)
        self.assertIn('assert_single_line_path "DUNE_UE4SS_PACKAGE_TRACE_ROUTE_SLOT_RECOVERY_VERIFY_JSON" "$route_slot_recovery_verify_json"', self.source)
        self.assertIn('assert_single_line_path "DUNE_UE4SS_PACKAGE_TRACE_ROUTE_SLOT_RECOVERY_VERIFY_MD" "$route_slot_recovery_verify_md"', self.source)
        self.assertIn('assert_single_line_path "TRACE_LOG" "$trace_log"', self.source)

        arm_start = self.source.index("do_arm() {")
        arm_body = self.source[arm_start : self.source.index("\n}", arm_start)]
        self.assertIn('assert_trace_output_paths "$trace_log"', arm_body)
        self.assertIn('remove_generated_file "$trace_log"', arm_body)
        self.assertIn('remove_generated_file "$gdb_out"', arm_body)

        stop_start = self.source.index("do_stop() {")
        stop_body = self.source[stop_start : self.source.index("\n}", stop_start)]
        self.assertIn("assert_trace_output_paths", stop_body)

        status_start = self.source.index("do_status() {")
        status_body = self.source[status_start : self.source.index("\n}", status_start)]
        self.assertIn('assert_trace_output_paths "$trace_log"', status_body)

        preflight_start = self.source.index("do_preflight() {")
        preflight_body = self.source[preflight_start : self.source.index("\n}", preflight_start)]
        self.assertIn('assert_trace_output_paths "$trace_log"', preflight_body)

    def test_runner_has_clean_detach_and_resume_guard(self):
        self.assertIn("kill_existing_gdb", self.source)
        self.assertIn("kill -CONT", self.source)
        self.assertIn("server_state", self.source)

    def test_runner_arm_fails_if_gdb_exits_immediately(self):
        arm_start = self.source.index("do_arm() {")
        arm_body = self.source[arm_start : self.source.index("\n}", arm_start)]

        self.assertIn("local gdb_pid=$!", arm_body)
        self.assertIn('echo "$gdb_pid" >"$gdb_pid_file"', arm_body)
        self.assertIn('if ! kill -0 "$gdb_pid" 2>/dev/null; then', arm_body)
        self.assertIn("package trace gdb exited before the arm window could be used", arm_body)
        self.assertIn('tail -80 "$gdb_out" 2>/dev/null >&2 || true', arm_body)
        self.assertIn('rm -f "$gdb_pid_file"', arm_body)
        self.assertIn("exit 1", arm_body)

    def test_runner_requires_allow_flag_for_final_native_call_confirmation(self):
        self.assertIn("assert_promotion_review_args", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_FINAL_NATIVE_CALL requires DUNE_UE4SS_PACKAGE_TRACE_ALLOW_NATIVE_INVOKE=1", self.source)
        status_start = self.source.index("do_status() {")
        status_body = self.source[status_start : self.source.index("\n}", status_start)]
        self.assertIn("assert_promotion_review_args", status_body)
        self.assertIn('--live-trace-runbook-json "$live_trace_runbook_json"', self.source)

    def test_runner_validates_anchor_and_limit_before_arm(self):
        arm_start = self.source.index("do_arm() {")
        arm_body = self.source[arm_start : self.source.index("\n}", arm_start)]

        self.assertIn("assert_runtime_selector_args", arm_body)
        self.assertIn("assert_signature_family", arm_body)
        self.assertIn("assert_anchor_args", arm_body)
        self.assertIn("assert_trace_limit", arm_body)
        self.assertIn("local count=0", self.source)
        self.assertIn("count=$((count + 1))", self.source)
        self.assertIn("DUNE_UE4SS_PACKAGE_TRACE_ANCHOR must include at least one package anchor", self.source)

    def test_runner_validates_runtime_selectors_before_stop_and_status(self):
        stop_start = self.source.index("do_stop() {")
        stop_body = self.source[stop_start : self.source.index("\n}", stop_start)]
        status_start = self.source.index("do_status() {")
        status_body = self.source[status_start : self.source.index("\n}", status_start)]

        self.assertIn("assert_runtime_selector_args", stop_body)
        self.assertIn("assert_runtime_selector_args", status_body)


if __name__ == "__main__":
    unittest.main()
