#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage:
  scripts/verify-client-probe-canary.sh --platform linux-client --prep-dir DIR --log LOG [--output-dir DIR] [--strict]
  scripts/verify-client-probe-canary.sh --platform windows --prep-dir DIR --log LOG [--output-dir DIR] [--strict]

Runs the post-canary verifier generated by prepare-ue-anchor-canary.py for a
native Linux or Windows/Proton client probe log and copies the resulting
readiness/gap artifacts into an evidence directory.
EOF
}

platform=""
prep_dir=""
loader_log=""
output_dir=""
strict=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    --platform)
      platform="${2:?missing value for --platform}"
      shift 2
      ;;
    --prep-dir)
      prep_dir="${2:?missing value for --prep-dir}"
      shift 2
      ;;
    --log)
      loader_log="${2:?missing value for --log}"
      shift 2
      ;;
    --output-dir)
      output_dir="${2:?missing value for --output-dir}"
      shift 2
      ;;
    --strict)
      strict=true
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

case "$platform" in
  linux-client|windows) ;;
  "")
    echo "missing --platform" >&2
    usage
    exit 2
    ;;
  *)
    echo "unsupported platform: $platform" >&2
    exit 2
    ;;
esac

if [ -z "$prep_dir" ]; then
  echo "missing --prep-dir" >&2
  usage
  exit 2
fi
if [ -z "$loader_log" ]; then
  echo "missing --log" >&2
  usage
  exit 2
fi

if [ ! -d "$prep_dir" ]; then
  echo "missing prepared canary dir: $prep_dir" >&2
  exit 2
fi
if [ ! -f "$prep_dir/ue-anchors.env" ]; then
  echo "missing prepared canary anchor env: $prep_dir/ue-anchors.env" >&2
  exit 2
fi
if [ ! -f "$loader_log" ]; then
  echo "missing client probe log: $loader_log" >&2
  exit 2
fi

verify_script="$prep_dir/post-canary-verify.sh"
if $strict; then
  verify_script="$prep_dir/post-canary-verify-strict.sh"
fi
if [ ! -x "$verify_script" ]; then
  echo "missing executable post-canary verifier: $verify_script" >&2
  exit 2
fi

if [ -z "$output_dir" ]; then
  stamp="$(date -u +%Y%m%dT%H%M%SZ)"
  output_dir="backups/client-probe-canary/$platform/$stamp"
fi
mkdir -p "$output_dir"

cp -a "$loader_log" "$output_dir/$(basename "$loader_log")"
cp -a "$prep_dir/ue-anchors.env" "$output_dir/ue-anchors.env"

set +e
"$verify_script" "$loader_log" > "$output_dir/post-canary-verify.log" 2>&1
verify_rc=$?
set -e

for name in \
  ue4ss-readiness.json \
  object-discovery-coverage.json \
  post-canary-summary.md \
  ue4ss-port-gaps.json \
  ue4ss-port-gaps.md; do
  if [ -f "$prep_dir/$name" ]; then
    cp -a "$prep_dir/$name" "$output_dir/$name"
  fi
done

{
  printf 'platform=%s\n' "$platform"
  printf 'prep_dir=%s\n' "$prep_dir"
  printf 'loader_log=%s\n' "$loader_log"
  printf 'strict=%s\n' "$strict"
  printf 'verify_script=%s\n' "$verify_script"
  printf 'verify_rc=%s\n' "$verify_rc"
  printf 'output_dir=%s\n' "$output_dir"
} > "$output_dir/summary.env"

printf 'platform=%s\n' "$platform"
printf 'verify_rc=%s\n' "$verify_rc"
printf 'output_dir=%s\n' "$output_dir"

exit "$verify_rc"
